#!/usr/bin/env python3
"""
Generates ShapeTable.java from the original Shape.java (MIT, see CREDITS.md), without the windows.

Usage: python3 tooling/shapes/gen_shape_table.py <ArchitectureCraft source folder>
"""
import os
import re
import sys

ROOT = os.path.join(os.path.dirname(__file__), "..", "..")
if len(sys.argv) < 2:
    sys.exit("Usage: gen_shape_table.py <ArchitectureCraft source folder>")
GTNH = sys.argv[1]
SHAPE_JAVA = os.path.join(GTNH, "src/main/java/gcewing/architecture/common/shape/Shape.java")
OUT = os.path.join(ROOT, "src/main/java/com/summax/apn/architecture/common/shape/ShapeTable.java")

# Constants whose snake case doesn't match the shape name.
RENAMES = {"RoofTileSE": "roof_tile_se", "SquareSE": "square_se", "SlabSE": "slab_se"}


def snake(name):
    if name in RENAMES:
        return RENAMES[name]
    m = re.match(r"(SlopeTile)([ABC]\d)(SE)?$", name)
    if m:
        return "slope_tile_" + m.group(2).lower() + ("_se" if m.group(3) else "")
    m = re.match(r"(ArchD)(\d[ABC]?)$", name)
    if m:
        return "arch_d" + m.group(2).lower()
    s = re.sub(r"(?<!^)(?=[A-Z])", "_", name).lower()
    return s.replace("_l_h", "_lh").replace("_r_h", "_rh")


def main():
    src = open(SHAPE_JAVA).read()
    body = src[src.index("public enum Shape {"):src.index("public int id;")]
    body = re.sub(r"\s+", " ", body)
    entries = re.findall(r"(\w+)\((\d+), \"[^\"]*\", (.+?), (\w+), (\d+), (\d+), (0x[0-9a-fA-F]+|\d+)(?:, ShapeFlags\.(\w+))?\)[,;]", body)
    lines = []
    for const, sid, kind, sym, used, made, occ, flag in entries:
        name = snake(const)
        profiles = "null"
        model = "null"
        m = re.match(r"(Model|Banister)\(\"(\w+)\"(?:, (\w+))?\)", kind)
        if m:
            k = "MODEL" if m.group(1) == "Model" else "BANISTER"
            model = '"' + m.group(2) + '"'
            if m.group(3):
                profiles = "Profiles." + m.group(3)
        elif kind == "Roof":
            k = "ROOF"
        elif kind in ("PlainWindow", "CornerWindow", "MullionWindow"):
            continue
        else:
            raise SystemExit("unknown kind " + kind)
        flags = {"": "0", "placeOffset": "PLACE_OFFSET", "placeUnderneath": "PLACE_UNDERNEATH"}[flag or ""]
        lines.append(f'        put("{name}", {sid}, Kind.{k}, {model}, Symmetry.{sym.upper()}, {flags}, {profiles}, {used}, {made}, {occ});')
    java = TEMPLATE.replace("%ENTRIES%", "\n".join(lines))
    open(OUT, "w").write(java)
    print("wrote", os.path.normpath(OUT), len(lines), "shapes")


TEMPLATE = """package com.summax.apn.architecture.common.shape;

import java.util.HashMap;
import java.util.Map;

/**
 * Generated by tooling/shapes/gen_shape_table.py, don't edit by hand.
 */
public final class ShapeTable {

    public enum Symmetry {NONE, UNILATERAL, BILATERAL, QUADRILATERAL}

    public enum Kind {MODEL, ROOF, BANISTER}

    public static final int PLACE_OFFSET = 1;
    public static final int PLACE_UNDERNEATH = 2;

    /**
     * Connection profiles of the faces, indexed by local face.
     */
    public enum Profile {
        END, LEFT_END, RIGHT_END, OFFSET_BOTTOM, OFFSET_TOP,
        ROOF_NONE, ROOF_LEFT, ROOF_RIGHT, ROOF_RIDGE, ROOF_VALLEY;

        public boolean matches(Profile other) {
            var opposite = switch (this) {
                case LEFT_END -> RIGHT_END;
                case RIGHT_END -> LEFT_END;
                case OFFSET_BOTTOM -> OFFSET_TOP;
                case OFFSET_TOP -> OFFSET_BOTTOM;
                case ROOF_LEFT -> ROOF_RIGHT;
                case ROOF_RIGHT -> ROOF_LEFT;
                default -> null;
            };
            return opposite != null ? opposite == other : this == other;
        }
    }

    static final class Profiles {
        static final Profile[] lrStraight = {null, null, null, null, Profile.RIGHT_END, Profile.LEFT_END};
        static final Profile[] lrCorner = {null, null, null, Profile.LEFT_END, Profile.RIGHT_END, null};
        static final Profile[] rlCorner = {null, null, Profile.RIGHT_END, null, null, Profile.LEFT_END};

        private Profiles() {
        }
    }

    /**
     * @param id            the icon index in the sawbench atlas.
     * @param model         the model name, null for roofs.
     * @param occlusionMask the solid 2x2x2 cubes of the shape.
     */
    public record Data(String name, int id, Kind kind, String model, Symmetry symmetry, int flags, Profile[] profiles,
                       int materialUsed, int itemsProduced, int occlusionMask) {

        public boolean hasFlag(int flag) {
            return (this.flags & flag) != 0;
        }

        public boolean banister() {
            return this.kind == Kind.BANISTER;
        }

        public Profile profileForLocalFace(int face) {
            if (this.kind == Kind.ROOF)
                return roofProfile(this.name, face);
            return this.profiles != null ? this.profiles[face] : null;
        }

        private static Profile roofProfile(String name, int face) {
            final int north = 2, south = 3, west = 4, east = 5;
            switch (name) {
                case "roof_tile":
                    if (face == east) return Profile.ROOF_LEFT;
                    if (face == west) return Profile.ROOF_RIGHT;
                    break;
                case "roof_outer_corner":
                    if (face == south) return Profile.ROOF_LEFT;
                    if (face == west) return Profile.ROOF_RIGHT;
                    break;
                case "roof_inner_corner":
                    if (face == east) return Profile.ROOF_LEFT;
                    if (face == north) return Profile.ROOF_RIGHT;
                    break;
                case "roof_ridge", "roof_smart_ridge":
                    return Profile.ROOF_RIDGE;
                case "roof_valley", "roof_smart_valley":
                    return Profile.ROOF_VALLEY;
                default:
                    break;
            }
            return Profile.ROOF_NONE;
        }
    }

    private static final Map<String, Data> DATA = new HashMap<>();

    static {
%ENTRIES%
    }

    private ShapeTable() {
    }

    private static void put(String name, int id, Kind kind, String model, Symmetry symmetry, int flags,
                            Profile[] profiles, int materialUsed, int itemsProduced, int occlusionMask) {
        DATA.put(name, new Data(name, id, kind, model, symmetry, flags, profiles, materialUsed, itemsProduced,
                occlusionMask));
    }

    public static Data get(String name) {
        return DATA.get(name);
    }
}
"""

if __name__ == "__main__":
    main()
