package com.summax.apn.architecture.common.shape;

import java.util.HashMap;
import java.util.Map;

/**
 * Generated by tooling/shapes/gen_shape_table.py, don't edit by hand.
 */
public final class ShapeTable {

    public enum Symmetry {NONE, UNILATERAL, BILATERAL, QUADRILATERAL}

    public enum Kind {MODEL, ROOF, BANISTER}

    public static final int PLACE_OFFSET = 1;
    public static final int PLACE_UNDERNEATH = 2;

    /**
     * Connection profiles of the faces, indexed by local face.
     */
    public enum Profile {
        END, LEFT_END, RIGHT_END, OFFSET_BOTTOM, OFFSET_TOP,
        ROOF_NONE, ROOF_LEFT, ROOF_RIGHT, ROOF_RIDGE, ROOF_VALLEY;

        public boolean matches(Profile other) {
            var opposite = switch (this) {
                case LEFT_END -> RIGHT_END;
                case RIGHT_END -> LEFT_END;
                case OFFSET_BOTTOM -> OFFSET_TOP;
                case OFFSET_TOP -> OFFSET_BOTTOM;
                case ROOF_LEFT -> ROOF_RIGHT;
                case ROOF_RIGHT -> ROOF_LEFT;
                default -> null;
            };
            return opposite != null ? opposite == other : this == other;
        }
    }

    static final class Profiles {
        static final Profile[] lrStraight = {null, null, null, null, Profile.RIGHT_END, Profile.LEFT_END};
        static final Profile[] lrCorner = {null, null, null, Profile.LEFT_END, Profile.RIGHT_END, null};
        static final Profile[] rlCorner = {null, null, Profile.RIGHT_END, null, null, Profile.LEFT_END};

        private Profiles() {
        }
    }

    /**
     * @param id            the icon index in the sawbench atlas.
     * @param model         the model name, null for roofs.
     * @param occlusionMask the solid 2x2x2 cubes of the shape.
     */
    public record Data(String name, int id, Kind kind, String model, Symmetry symmetry, int flags, Profile[] profiles,
                       int materialUsed, int itemsProduced, int occlusionMask) {

        public boolean hasFlag(int flag) {
            return (this.flags & flag) != 0;
        }

        public boolean banister() {
            return this.kind == Kind.BANISTER;
        }

        public Profile profileForLocalFace(int face) {
            if (this.kind == Kind.ROOF)
                return roofProfile(this.name, face);
            return this.profiles != null ? this.profiles[face] : null;
        }

        private static Profile roofProfile(String name, int face) {
            final int north = 2, south = 3, west = 4, east = 5;
            switch (name) {
                case "roof_tile":
                    if (face == east) return Profile.ROOF_LEFT;
                    if (face == west) return Profile.ROOF_RIGHT;
                    break;
                case "roof_outer_corner":
                    if (face == south) return Profile.ROOF_LEFT;
                    if (face == west) return Profile.ROOF_RIGHT;
                    break;
                case "roof_inner_corner":
                    if (face == east) return Profile.ROOF_LEFT;
                    if (face == north) return Profile.ROOF_RIGHT;
                    break;
                case "roof_ridge", "roof_smart_ridge":
                    return Profile.ROOF_RIDGE;
                case "roof_valley", "roof_smart_valley":
                    return Profile.ROOF_VALLEY;
                default:
                    break;
            }
            return Profile.ROOF_NONE;
        }
    }

    private static final Map<String, Data> DATA = new HashMap<>();

    static {
        put("roof_tile", 0, Kind.ROOF, null, Symmetry.BILATERAL, 0, null, 1, 2, 0xcf);
        put("roof_outer_corner", 1, Kind.ROOF, null, Symmetry.UNILATERAL, 0, null, 1, 3, 0x4f);
        put("roof_inner_corner", 2, Kind.ROOF, null, Symmetry.UNILATERAL, 0, null, 2, 3, 0xdf);
        put("roof_ridge", 3, Kind.ROOF, null, Symmetry.BILATERAL, 0, null, 1, 4, 0x0f);
        put("roof_smart_ridge", 4, Kind.ROOF, null, Symmetry.QUADRILATERAL, 0, null, 1, 2, 0x0f);
        put("roof_valley", 5, Kind.ROOF, null, Symmetry.BILATERAL, 0, null, 1, 2, 0xff);
        put("roof_smart_valley", 6, Kind.ROOF, null, Symmetry.QUADRILATERAL, 0, null, 1, 1, 0xff);
        put("roof_overhang", 7, Kind.MODEL, "roof_overhang", Symmetry.BILATERAL, 0, null, 1, 2, 0xcf);
        put("roof_overhang_outer_corner", 8, Kind.MODEL, "roof_overhang_outer_corner", Symmetry.UNILATERAL, 0, null, 1, 3, 0x4f);
        put("roof_overhang_inner_corner", 9, Kind.MODEL, "roof_overhang_inner_corner", Symmetry.UNILATERAL, 0, null, 2, 3, 0xdf);
        put("cylinder", 10, Kind.MODEL, "cylinder_full_r8h16", Symmetry.QUADRILATERAL, 0, null, 1, 1, 0xff);
        put("cylinder_half", 11, Kind.MODEL, "cylinder_half_r8h16", Symmetry.BILATERAL, 0, null, 1, 1, 0xcc);
        put("cylinder_quarter", 12, Kind.MODEL, "cylinder_quarter_r8h16", Symmetry.UNILATERAL, 0, null, 1, 1, 0x44);
        put("cylinder_large_quarter", 13, Kind.MODEL, "cylinder_quarter_r16h16", Symmetry.UNILATERAL, 0, null, 1, 1, 0xff);
        put("anticylinder_large_quarter", 14, Kind.MODEL, "round_inner_corner", Symmetry.UNILATERAL, 0, null, 1, 2, 0xdd);
        put("pillar", 15, Kind.MODEL, "cylinder_r6h16", Symmetry.QUADRILATERAL, 0, null, 1, 1, 0x106);
        put("post", 16, Kind.MODEL, "cylinder_r4h16", Symmetry.QUADRILATERAL, 0, null, 1, 4, 0x104);
        put("pole", 17, Kind.MODEL, "cylinder_r2h16", Symmetry.QUADRILATERAL, 0, null, 1, 16, 0x102);
        put("bevelled_outer_corner", 18, Kind.MODEL, "bevelled_outer_corner", Symmetry.UNILATERAL, 0, null, 1, 3, 0x4f);
        put("bevelled_inner_corner", 19, Kind.MODEL, "bevelled_inner_corner", Symmetry.UNILATERAL, 0, null, 1, 1, 0xdf);
        put("pillar_base", 20, Kind.MODEL, "pillar_base", Symmetry.QUADRILATERAL, 0, null, 1, 1, 0xff);
        put("doric_capital", 21, Kind.MODEL, "doric_capital", Symmetry.QUADRILATERAL, 0, null, 1, 1, 0xff);
        put("ionic_capital", 22, Kind.MODEL, "ionic_capital", Symmetry.BILATERAL, 0, null, 1, 1, 0xff);
        put("corinthian_capital", 23, Kind.MODEL, "corinthian_capital", Symmetry.QUADRILATERAL, 0, null, 1, 1, 0xff);
        put("doric_triglyph", 24, Kind.MODEL, "doric_triglyph", Symmetry.BILATERAL, 0, Profiles.lrStraight, 1, 1, 0xff);
        put("doric_triglyph_corner", 25, Kind.MODEL, "doric_triglyph_corner", Symmetry.BILATERAL, 0, Profiles.lrCorner, 1, 1, 0xff);
        put("doric_metope", 26, Kind.MODEL, "doric_metope", Symmetry.BILATERAL, 0, Profiles.lrStraight, 1, 1, 0xff);
        put("architrave", 27, Kind.MODEL, "architrave", Symmetry.BILATERAL, 0, Profiles.lrStraight, 1, 1, 0xff);
        put("architrave_corner", 28, Kind.MODEL, "architrave_corner", Symmetry.UNILATERAL, 0, Profiles.lrCorner, 1, 1, 0xff);
        put("sphere_full", 33, Kind.MODEL, "sphere_full_r8", Symmetry.QUADRILATERAL, 0, null, 1, 1, 0xff);
        put("sphere_half", 34, Kind.MODEL, "sphere_half_r8", Symmetry.QUADRILATERAL, 0, null, 1, 2, 0x0f);
        put("sphere_quarter", 35, Kind.MODEL, "sphere_quarter_r8", Symmetry.BILATERAL, 0, null, 1, 4, 0x0c);
        put("sphere_eighth", 36, Kind.MODEL, "sphere_eighth_r8", Symmetry.UNILATERAL, 0, null, 1, 8, 0x04);
        put("sphere_eighth_large", 37, Kind.MODEL, "sphere_eighth_r16", Symmetry.UNILATERAL, 0, null, 1, 1, 0xff);
        put("sphere_eighth_large_rev", 38, Kind.MODEL, "sphere_eighth_r16_rev", Symmetry.UNILATERAL, 0, null, 1, 1, 0xdf);
        put("roof_overhang_gable_lh", 40, Kind.MODEL, "roof_overhang_gable_lh", Symmetry.BILATERAL, 0, null, 1, 4, 0x48);
        put("roof_overhang_gable_rh", 41, Kind.MODEL, "roof_overhang_gable_rh", Symmetry.BILATERAL, 0, null, 1, 4, 0x84);
        put("roof_overhang_gable_end_lh", 42, Kind.MODEL, "roof_overhang_gable_end_lh", Symmetry.BILATERAL, 0, null, 1, 4, 0x48);
        put("roof_overhang_gable_end_rh", 43, Kind.MODEL, "roof_overhang_gable_end_rh", Symmetry.BILATERAL, 0, null, 1, 4, 0x48);
        put("roof_overhang_ridge", 44, Kind.MODEL, "roof_overhang_gable_ridge", Symmetry.BILATERAL, 0, null, 1, 4, 0x0c);
        put("roof_overhang_valley", 45, Kind.MODEL, "roof_overhang_gable_valley", Symmetry.BILATERAL, 0, null, 1, 4, 0xcc);
        put("cornice_lh", 50, Kind.MODEL, "cornice_lh", Symmetry.BILATERAL, 0, null, 1, 4, 0x48);
        put("cornice_rh", 51, Kind.MODEL, "cornice_rh", Symmetry.BILATERAL, 0, null, 1, 4, 0x84);
        put("cornice_end_lh", 52, Kind.MODEL, "cornice_end_lh", Symmetry.BILATERAL, 0, null, 1, 4, 0x48);
        put("cornice_end_rh", 53, Kind.MODEL, "cornice_end_rh", Symmetry.BILATERAL, 0, null, 1, 4, 0x48);
        put("cornice_ridge", 54, Kind.MODEL, "cornice_ridge", Symmetry.BILATERAL, 0, null, 1, 4, 0x0c);
        put("cornice_valley", 55, Kind.MODEL, "cornice_valley", Symmetry.BILATERAL, 0, null, 1, 4, 0xcc);
        put("cornice_bottom", 56, Kind.MODEL, "cornice_bottom", Symmetry.BILATERAL, 0, null, 1, 4, 0x0c);
        put("cladding_sheet", 60, Kind.MODEL, "cladding", Symmetry.NONE, 0, null, 1, 1, 0x0c);
        put("arch_d1", 61, Kind.MODEL, "arch_d1", Symmetry.BILATERAL, PLACE_UNDERNEATH, null, 1, 1, 0xff);
        put("arch_d2", 62, Kind.MODEL, "arch_d2", Symmetry.BILATERAL, PLACE_UNDERNEATH, null, 1, 2, 0xfc);
        put("arch_d3a", 63, Kind.MODEL, "arch_d3a", Symmetry.BILATERAL, PLACE_UNDERNEATH, null, 1, 2, 0xcc);
        put("arch_d3b", 64, Kind.MODEL, "arch_d3b", Symmetry.BILATERAL, PLACE_UNDERNEATH, null, 1, 1, 0xfc);
        put("arch_d3c", 65, Kind.MODEL, "arch_d3c", Symmetry.BILATERAL, PLACE_UNDERNEATH, null, 1, 1, 0xff);
        put("arch_d4a", 66, Kind.MODEL, "arch_d4a", Symmetry.BILATERAL, PLACE_UNDERNEATH, null, 1, 2, 0xcc);
        put("arch_d4b", 67, Kind.MODEL, "arch_d4b", Symmetry.BILATERAL, PLACE_UNDERNEATH, null, 1, 1, 0xfc);
        put("arch_d4c", 68, Kind.MODEL, "arch_d4c", Symmetry.BILATERAL, PLACE_UNDERNEATH, null, 1, 2, 0x0);
        put("banister_plain_bottom", 70, Kind.BANISTER, "balustrade_stair_plain_bottom", Symmetry.BILATERAL, PLACE_OFFSET, null, 1, 10, 0x0);
        put("banister_plain", 71, Kind.BANISTER, "balustrade_stair_plain", Symmetry.BILATERAL, PLACE_OFFSET, null, 1, 10, 0x0);
        put("banister_plain_top", 72, Kind.BANISTER, "balustrade_stair_plain_top", Symmetry.BILATERAL, PLACE_OFFSET, null, 1, 10, 0x0);
        put("balustrade_fancy", 73, Kind.MODEL, "balustrade_fancy", Symmetry.BILATERAL, 0, null, 1, 5, 0x0);
        put("balustrade_fancy_corner", 74, Kind.MODEL, "balustrade_fancy_corner", Symmetry.UNILATERAL, 0, null, 1, 2, 0x0);
        put("balustrade_fancy_with_newel", 75, Kind.MODEL, "balustrade_fancy_with_newel", Symmetry.BILATERAL, 0, null, 1, 3, 0x0);
        put("balustrade_fancy_newel", 76, Kind.MODEL, "balustrade_fancy_newel", Symmetry.UNILATERAL, 0, null, 1, 4, 0x0);
        put("balustrade_plain", 77, Kind.MODEL, "balustrade_plain", Symmetry.BILATERAL, 0, null, 1, 10, 0x0);
        put("balustrade_plain_outer_corner", 78, Kind.MODEL, "balustrade_plain_outer_corner", Symmetry.UNILATERAL, 0, null, 1, 4, 0x0);
        put("balustrade_plain_with_newel", 79, Kind.MODEL, "balustrade_plain_with_newel", Symmetry.BILATERAL, 0, null, 1, 6, 0x0);
        put("banister_plain_end", 80, Kind.BANISTER, "balustrade_stair_plain_end", Symmetry.BILATERAL, PLACE_OFFSET, null, 1, 8, 0x0);
        put("banister_fancy_newel_tall", 81, Kind.MODEL, "balustrade_fancy_newel_tall", Symmetry.UNILATERAL, 0, null, 1, 2, 0x0);
        put("balustrade_plain_inner_corner", 82, Kind.MODEL, "balustrade_plain_inner_corner", Symmetry.UNILATERAL, 0, null, 1, 8, 0x0);
        put("balustrade_plain_end", 83, Kind.BANISTER, "balustrade_plain_end", Symmetry.BILATERAL, PLACE_OFFSET, null, 1, 8, 0x0);
        put("banister_fancy_bottom", 84, Kind.BANISTER, "balustrade_stair_fancy_bottom", Symmetry.BILATERAL, PLACE_OFFSET, null, 1, 5, 0x0);
        put("banister_fancy", 85, Kind.BANISTER, "balustrade_stair_fancy", Symmetry.BILATERAL, PLACE_OFFSET, null, 1, 5, 0x0);
        put("banister_fancy_top", 86, Kind.BANISTER, "balustrade_stair_fancy_top", Symmetry.BILATERAL, PLACE_OFFSET, null, 1, 5, 0x0);
        put("banister_fancy_end", 87, Kind.BANISTER, "balustrade_stair_fancy_end", Symmetry.BILATERAL, PLACE_OFFSET, null, 1, 2, 0x0);
        put("banister_plain_inner_corner", 88, Kind.MODEL, "balustrade_stair_plain_inner_corner", Symmetry.UNILATERAL, 0, null, 1, 6, 0x0);
        put("slab", 90, Kind.MODEL, "slab", Symmetry.QUADRILATERAL, 0, null, 1, 2, 0x0f);
        put("stairs", 91, Kind.MODEL, "stairs", Symmetry.BILATERAL, 0, Profiles.lrStraight, 3, 4, 0xcf);
        put("stairs_outer_corner", 92, Kind.MODEL, "stairs_outer_corner", Symmetry.UNILATERAL, 0, Profiles.lrCorner, 2, 3, 0x4f);
        put("stairs_inner_corner", 93, Kind.MODEL, "stairs_inner_corner", Symmetry.UNILATERAL, 0, Profiles.rlCorner, 1, 1, 0xdf);
        put("slope_tile_a1", 94, Kind.ROOF, null, Symmetry.BILATERAL, 0, null, 1, 1, 0xcf);
        put("slope_tile_a2", 95, Kind.ROOF, null, Symmetry.BILATERAL, 0, null, 1, 3, 0x0f);
        put("slope_tile_b1", 96, Kind.ROOF, null, Symmetry.BILATERAL, 0, null, 1, 1, 0xff);
        put("slope_tile_b2", 97, Kind.ROOF, null, Symmetry.BILATERAL, 0, null, 1, 2, 0xcf);
        put("slope_tile_b3", 98, Kind.ROOF, null, Symmetry.BILATERAL, 0, null, 1, 3, 0x0f);
        put("slope_tile_c1", 99, Kind.ROOF, null, Symmetry.BILATERAL, 0, null, 1, 1, 0xff);
        put("slope_tile_c2", 100, Kind.ROOF, null, Symmetry.BILATERAL, 0, null, 1, 2, 0xcf);
        put("slope_tile_c3", 101, Kind.ROOF, null, Symmetry.BILATERAL, 0, null, 1, 3, 0x0f);
        put("slope_tile_c4", 102, Kind.ROOF, null, Symmetry.BILATERAL, 0, null, 1, 4, 0x0f);
        put("slope_tile_a1_se", 103, Kind.ROOF, null, Symmetry.BILATERAL, 0, null, 1, 1, 0xcf);
        put("slope_tile_a2_se", 104, Kind.ROOF, null, Symmetry.BILATERAL, 0, null, 1, 3, 0x0f);
        put("slope_tile_b1_se", 105, Kind.ROOF, null, Symmetry.BILATERAL, 0, null, 1, 1, 0xff);
        put("slope_tile_b2_se", 106, Kind.ROOF, null, Symmetry.BILATERAL, 0, null, 1, 2, 0xcf);
        put("slope_tile_b3_se", 107, Kind.ROOF, null, Symmetry.BILATERAL, 0, null, 1, 3, 0x0f);
        put("slope_tile_c1_se", 108, Kind.ROOF, null, Symmetry.BILATERAL, 0, null, 1, 1, 0xff);
        put("slope_tile_c2_se", 109, Kind.ROOF, null, Symmetry.BILATERAL, 0, null, 1, 2, 0xcf);
        put("slope_tile_c3_se", 110, Kind.ROOF, null, Symmetry.BILATERAL, 0, null, 1, 3, 0x0f);
        put("slope_tile_c4_se", 111, Kind.ROOF, null, Symmetry.BILATERAL, 0, null, 1, 4, 0x0f);
        put("roof_tile_se", 112, Kind.ROOF, null, Symmetry.BILATERAL, 0, null, 1, 2, 0xcf);
        put("square_se", 113, Kind.MODEL, "square", Symmetry.QUADRILATERAL, 0, null, 1, 1, 0xff);
        put("slab_se", 114, Kind.MODEL, "slab", Symmetry.QUADRILATERAL, 0, null, 1, 2, 0x0f);
        put("angled_roof_ridge", 115, Kind.MODEL, "angled_roof_ridge", Symmetry.BILATERAL, 0, null, 1, 4, 0x0f);
        put("double_roof_tile", 116, Kind.MODEL, "double_roof_tile", Symmetry.BILATERAL, 0, null, 1, 2, 0xcf);
    }

    private ShapeTable() {
    }

    private static void put(String name, int id, Kind kind, String model, Symmetry symmetry, int flags,
                            Profile[] profiles, int materialUsed, int itemsProduced, int occlusionMask) {
        DATA.put(name, new Data(name, id, kind, model, symmetry, flags, profiles, materialUsed, itemsProduced,
                occlusionMask));
    }

    public static Data get(String name) {
        return DATA.get(name);
    }
}
